import { Book, Category, Publisher, Review, Branch } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "academic",
    name: "Academic",
    icon: "GraduationCap",
    count: 320,
    gradient: "from-blue-600 to-indigo-700",
    subcategories: ["CBSE", "ICSE", "State Board", "University Guides"]
  },
  {
    id: "school",
    name: "School Books",
    icon: "BookOpen",
    count: 450,
    gradient: "from-sky-500 to-blue-600",
    subcategories: ["NCERT", "Reference Books", "Kindergarten", "Workbooks"]
  },
  {
    id: "engineering",
    name: "Engineering",
    icon: "Cpu",
    count: 250,
    gradient: "from-purple-600 to-indigo-800",
    subcategories: ["Computer Science", "Electronics", "Mechanical", "Civil"]
  },
  {
    id: "medical",
    name: "Medical",
    icon: "HeartPulse",
    count: 180,
    gradient: "from-emerald-500 to-teal-600",
    subcategories: ["MBBS Essentials", "Anatomy", "Pharmacology", "Nursing"]
  },
  {
    id: "competitive",
    name: "Competitive Exams",
    icon: "Trophy",
    count: 290,
    gradient: "from-amber-500 to-orange-600",
    subcategories: ["JEE/NEET", "UPSC Civil Services", "Banking & SSC", "GATE"]
  },
  {
    id: "malayalam",
    name: "Malayalam Literature",
    icon: "PenTool",
    count: 350,
    gradient: "from-red-500 to-rose-600",
    subcategories: ["Novels", "Poetry", "Short Stories", "History"]
  },
  {
    id: "english",
    name: "English Literature",
    icon: "Languages",
    count: 400,
    gradient: "from-indigo-500 to-violet-600",
    subcategories: ["Classics", "Modern Fiction", "Poetry", "Drama"]
  },
  {
    id: "children",
    name: "Children Books",
    icon: "Sparkles",
    count: 150,
    gradient: "from-pink-500 to-rose-500",
    subcategories: ["Storybooks", "Coloring & Drawing", "Puzzles", "Fables"]
  },
  {
    id: "business",
    name: "Business & Commerce",
    icon: "Briefcase",
    count: 120,
    gradient: "from-cyan-500 to-blue-600",
    subcategories: ["Marketing", "Accounting", "Economics", "Management"]
  },
  {
    id: "self-help",
    name: "Self Help",
    icon: "Smile",
    count: 95,
    gradient: "from-teal-500 to-emerald-600",
    subcategories: ["Motivation", "Mindset", "Time Management", "Habits"]
  }
];

export const PUBLISHERS: Publisher[] = [
  {
    id: "oxford",
    name: "Oxford University Press",
    logoText: "OUP",
    description: "World-class educational content and reference materials supporting high-level academic research and school curricula.",
    count: 184,
    bgColor: "bg-blue-900 text-white"
  },
  {
    id: "pearson",
    name: "Pearson Education",
    logoText: "Pearson",
    description: "Global leader in educational publishing, providing textbooks, digital materials, and learning systems for all levels.",
    count: 220,
    bgColor: "bg-teal-700 text-white"
  },
  {
    id: "mcgraw-hill",
    name: "McGraw Hill",
    logoText: "MHE",
    description: "Premium engineering, mathematics, medical, and competitive test prep guides trusted by millions of students.",
    count: 142,
    bgColor: "bg-red-800 text-white"
  },
  {
    id: "s-chand",
    name: "S Chand Publishing",
    logoText: "S.Chand",
    description: "India's premier school and college textbook publishing house with trusted reference study guides.",
    count: 310,
    bgColor: "bg-amber-600 text-white"
  },
  {
    id: "arihant",
    name: "Arihant Publications",
    logoText: "Arihant",
    description: "Highly focused self-study books and solved papers for major national-level competitive examinations.",
    count: 285,
    bgColor: "bg-orange-700 text-white"
  },
  {
    id: "dc-books",
    name: "DC Books",
    logoText: "DCB",
    description: "Kerala's largest publisher of literature, poetry, translating international masterpieces into Malayalam.",
    count: 420,
    bgColor: "bg-emerald-900 text-white"
  },
  {
    id: "mathrubhumi",
    name: "Mathrubhumi Books",
    logoText: "MBI",
    description: "Acclaimed publication house bringing out classics, children books, and rich historical accounts in Malayalam.",
    count: 195,
    bgColor: "bg-red-600 text-white"
  }
];

export const BOOKS: Book[] = [
  {
    id: "engg-math",
    title: "Advanced Engineering Mathematics",
    author: "Erwin Kreyszig",
    publisher: "Oxford University Press",
    category: "Engineering",
    subcategory: "Computer Science",
    isbn: "978-0470458365",
    edition: "10th Edition",
    language: "English",
    pages: 1150,
    description: "This market-leading text is known for its comprehensive coverage, careful and correct mathematics, outstanding exercises, and self-contained subject matter parts for maximum flexibility. Excellent for CSE, ECE, and Mechanical engineers.",
    price: 850,
    oldPrice: 1200,
    offerBadge: "30% OFF",
    rating: 4.8,
    coverColor: "from-blue-700 to-indigo-950",
    coverEmoji: "📐",
    isNewArrival: false,
    isBestSeller: true,
    isRecommended: true,
    salesCount: 1240,
    rank: 1
  },
  {
    id: "physics-hcv",
    title: "Concepts of Physics (Vol 1 & 2)",
    author: "H.C. Verma",
    publisher: "S Chand Publishing",
    category: "School Books",
    subcategory: "Reference Books",
    isbn: "978-8177091878",
    edition: "Latest Edition",
    language: "English",
    pages: 460,
    description: "Concepts of Physics is an iconic handbook of physics fundamentals. It is highly valued by High School and competitive JEE/NEET aspirants for its clear explanation of physical laws and brilliantly designed quantitative exercises.",
    price: 420,
    oldPrice: 500,
    offerBadge: "16% OFF",
    rating: 4.9,
    coverColor: "from-amber-600 to-orange-800",
    coverEmoji: "⚛️",
    isNewArrival: false,
    isBestSeller: true,
    isRecommended: true,
    salesCount: 3500,
    rank: 2
  },
  {
    id: "usmle-step1",
    title: "First Aid for the USMLE Step 1",
    author: "Tao Le, Vikas Bhushan",
    publisher: "McGraw Hill",
    category: "Medical",
    subcategory: "MBBS Essentials",
    isbn: "978-1264257882",
    edition: "2026 Edition",
    language: "English",
    pages: 840,
    description: "The time-tested, premium blueprint of medical high-yield topics and Mnemonics. This is the absolute bible for MBBS students preparing for USMLE Step 1, loaded with color illustrations and high-yield clinical correlations.",
    price: 1650,
    oldPrice: 2200,
    offerBadge: "25% OFF",
    rating: 4.9,
    coverColor: "from-rose-700 to-red-950",
    coverEmoji: "🩺",
    isNewArrival: true,
    isBestSeller: true,
    isRecommended: true,
    salesCount: 920,
    rank: 3
  },
  {
    id: "brief-history-time",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    publisher: "Oxford University Press",
    category: "English Literature",
    subcategory: "Classics",
    isbn: "978-0553380163",
    edition: "Bantam Edition",
    language: "English",
    pages: 212,
    description: "A landmark volume in science writing by one of the great minds of our time. Stephen Hawking explores the mysteries of black holes, expanding space, and the origins of the cosmos in plain language everyone can enjoy.",
    price: 349,
    oldPrice: 499,
    offerBadge: "30% OFF",
    rating: 4.7,
    coverColor: "from-purple-800 to-slate-950",
    coverEmoji: "🌌",
    isNewArrival: false,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 1800
  },
  {
    id: "comp-awareness",
    title: "Objective Computer Awareness",
    author: "Arihant Experts",
    publisher: "Arihant Publications",
    category: "Competitive Exams",
    subcategory: "Banking & SSC",
    isbn: "978-9325290617",
    edition: "Revise 2025",
    language: "English",
    pages: 240,
    description: "An incredibly useful reference resource for Bank PO, Clerk, SSC, Railway, and State Government competitive exams. Includes practice sets, standard vocabulary, and previous years' solved papers.",
    price: 180,
    oldPrice: 250,
    offerBadge: "28% OFF",
    rating: 4.3,
    coverColor: "from-teal-600 to-emerald-900",
    coverEmoji: "💻",
    isNewArrival: false,
    isBestSeller: false,
    isRecommended: false,
    salesCount: 1400
  },
  {
    id: "db-systems",
    title: "Fundamentals of Database Systems",
    author: "Ramez Elmasri, Shamkant B. Navathe",
    publisher: "Pearson Education",
    category: "Engineering",
    subcategory: "Computer Science",
    isbn: "978-0133970777",
    edition: "7th Edition",
    language: "English",
    pages: 1280,
    description: "The definitive introduction to database systems design, implementation, and management. Contains modern modules on NoSQL, relational database queries, query processing, and data warehousing.",
    price: 720,
    oldPrice: 999,
    offerBadge: "28% OFF",
    rating: 4.5,
    coverColor: "from-sky-700 to-indigo-900",
    coverEmoji: "🗄️",
    isNewArrival: false,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 750
  },
  {
    id: "indulekha-dcb",
    title: "Indulekha",
    author: "O. Chandu Menon",
    publisher: "DC Books",
    category: "Malayalam Literature",
    subcategory: "Novels",
    isbn: "978-8171301386",
    edition: "DC Deluxe Edition",
    language: "Malayalam",
    pages: 310,
    description: "Published in 1889, Indulekha was the first major novel in the Malayalam language. It depicts a beautiful, educated woman's struggle against regressive feudal caste structures and forced marriages in historical Malabar.",
    price: 190,
    oldPrice: 220,
    offerBadge: "14% OFF",
    rating: 4.8,
    coverColor: "from-emerald-700 to-teal-950",
    coverEmoji: "🌴",
    isNewArrival: false,
    isBestSeller: true,
    isRecommended: true,
    salesCount: 2200,
    rank: 4
  },
  {
    id: "wings-fire",
    title: "Wings of Fire: An Autobiography",
    author: "A.P.J. Abdul Kalam",
    publisher: "S Chand Publishing",
    category: "Academic",
    subcategory: "University Guides",
    isbn: "978-8173711466",
    edition: "Classic Reprint",
    language: "English",
    pages: 180,
    description: "The powerful autobiography of former President of India Dr. A.P.J. Abdul Kalam. It details his humble early life, his tireless work in Indian aerospace research, and his journey to becoming the Missile Man of India.",
    price: 280,
    oldPrice: 350,
    offerBadge: "20% OFF",
    rating: 4.9,
    coverColor: "from-blue-600 to-orange-900",
    coverEmoji: "🚀",
    isNewArrival: false,
    isBestSeller: true,
    isRecommended: true,
    salesCount: 4100,
    rank: 5
  },
  {
    id: "wren-martin",
    title: "High School English Grammar & Composition",
    author: "Wren & Martin",
    publisher: "S Chand Publishing",
    category: "School Books",
    subcategory: "Reference Books",
    isbn: "978-9352530144",
    edition: "Multicolor Edition",
    language: "English",
    pages: 450,
    description: "Wren and Martin's English Grammar is the gold standard guide for grammar, synthesis, and creative composition. Features extensive practice tests and answers for students and competitive exam aspirants.",
    price: 250,
    oldPrice: 350,
    offerBadge: "30% OFF",
    rating: 4.7,
    coverColor: "from-indigo-700 to-purple-950",
    coverEmoji: "✍️",
    isNewArrival: true,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 2900
  },
  {
    id: "clrs-algorithms",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    publisher: "Pearson Education",
    category: "Engineering",
    subcategory: "Computer Science",
    isbn: "978-0262033848",
    edition: "4th Edition",
    language: "English",
    pages: 1312,
    description: "Widely known as CLRS, this book covers a deep, rigorous, and exhaustive study of modern computer algorithms. Includes pseudocode, dynamic programming, and network flows.",
    price: 1100,
    oldPrice: 1500,
    offerBadge: "26% OFF",
    rating: 4.8,
    coverColor: "from-slate-700 to-slate-900",
    coverEmoji: "⚙️",
    isNewArrival: true,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 810
  },
  {
    id: "diary-wimpy-kid",
    title: "Diary of a Wimpy Kid: Big Shot",
    author: "Jeff Kinney",
    publisher: "Pearson Education",
    category: "Children Books",
    subcategory: "Storybooks",
    isbn: "978-1419749156",
    edition: "Hardcover Book 16",
    language: "English",
    pages: 224,
    description: "In Big Shot, book 16 of the Diary of a Wimpy Kid series, Greg Heffley and sports just don't mix. After a disastrous field day competition, Greg decides to officially retire from his athletic career.",
    price: 299,
    oldPrice: 399,
    offerBadge: "25% OFF",
    rating: 4.7,
    coverColor: "from-yellow-500 to-amber-700",
    coverEmoji: "👦",
    isNewArrival: true,
    isBestSeller: false,
    isRecommended: false,
    salesCount: 620
  },
  {
    id: "marketing-kotler",
    title: "Principles of Marketing",
    author: "Philip Kotler, Gary Armstrong",
    publisher: "Pearson Education",
    category: "Business & Commerce",
    subcategory: "Marketing",
    isbn: "978-0134492513",
    edition: "17th Edition",
    language: "English",
    pages: 730,
    description: "Kotler's guide provides an immersive look at customer value, consumer journeys, and global marketing strategies in the digital era.",
    price: 890,
    oldPrice: 1300,
    offerBadge: "31% OFF",
    rating: 4.6,
    coverColor: "from-violet-700 to-fuchsia-950",
    coverEmoji: "📈",
    isNewArrival: false,
    isBestSeller: false,
    isRecommended: false,
    salesCount: 540
  },
  {
    id: "think-grow-rich",
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    publisher: "Arihant Publications",
    category: "Self Help",
    subcategory: "Motivation",
    isbn: "978-8172242138",
    edition: "Standard Print",
    language: "English",
    pages: 320,
    description: "The original growth mindset guide. Written during the Great Depression, Napoleon Hill compiles wisdom from over 500 self-made millionaires.",
    price: 150,
    oldPrice: 220,
    offerBadge: "31% OFF",
    rating: 4.5,
    coverColor: "from-emerald-800 to-yellow-900",
    coverEmoji: "🪙",
    isNewArrival: false,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 1600
  },
  {
    id: "modern-india-bipan",
    title: "History of Modern India",
    author: "Bipan Chandra",
    publisher: "Mathrubhumi Books",
    category: "Competitive Exams",
    subcategory: "UPSC Civil Services",
    isbn: "978-8125036845",
    edition: "Paperback Edition",
    language: "English",
    pages: 360,
    description: "Highly readable and analytical book on modern Indian history. Essential curriculum book for students preparing for Civil Services and State Administrative examinations.",
    price: 310,
    oldPrice: 400,
    offerBadge: "22% OFF",
    rating: 4.8,
    coverColor: "from-rose-600 to-amber-900",
    coverEmoji: "📜",
    isNewArrival: true,
    isBestSeller: false,
    isRecommended: true,
    salesCount: 1100
  }
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    name: "Dr. Sandeep Kurup",
    role: "Professor of Medicine",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "Students Book Stall is my go-to choice for academic books for my students. Their stock is always updated and the same-day delivery option works like magic!",
    bookTitle: "First Aid for the USMLE Step 1"
  },
  {
    id: "rev-2",
    name: "Sneha Radhakrishnan",
    role: "B.Tech Student, CSE",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "Got my standard text books on Computer Algorithms and Database Systems at a 30% discount. Outstanding service and the packaging was waterproof!",
    bookTitle: "Introduction to Algorithms"
  },
  {
    id: "rev-3",
    name: "K. R. Harikumar",
    role: "High School Teacher",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    rating: 5,
    text: "Wren & Martin and HC Verma physics volumes are always in stock. I recommend parents to pre-order their textbook kits from Students Book Stall before school begins.",
    bookTitle: "High School English Grammar & Composition"
  }
];

export const BRANCHES: Branch[] = [
  {
    name: "Kottayam Head Office",
    address: "T.B. Road, Near KSRTC Bus Stand, Kottayam, Kerala - 686001",
    phone: "+91 481 2561234",
    whatsapp: "+91 9447012345",
    email: "kottayam@studentsbookstall.com",
    timing: "09:00 AM - 08:30 PM (Mon - Sat)"
  },
  {
    name: "Ernakulam Branch",
    address: "Press Club Road, Near YMCA, Kochi, Kerala - 682011",
    phone: "+91 484 2364567",
    whatsapp: "+91 9447067890",
    email: "ernakulam@studentsbookstall.com",
    timing: "09:30 AM - 08:00 PM (Mon - Sat)"
  },
  {
    name: "Trivandrum Branch",
    address: "Overbridge Junction, M.G. Road, Thiruvananthapuram, Kerala - 695001",
    phone: "+91 471 2478901",
    whatsapp: "+91 9447098765",
    email: "trivandrum@studentsbookstall.com",
    timing: "09:00 AM - 08:00 PM (Mon - Sun)"
  }
];

export const COMBOS = [
  {
    id: "combo-1",
    title: "Engineering Computer Science Sem 1 Kit",
    booksCount: 3,
    originalPrice: 2670,
    price: 2150,
    saveAmount: 520,
    booksIncluded: ["Advanced Engineering Mathematics", "Fundamentals of Database Systems", "Introduction to Algorithms"],
    badge: "CS Semester Essential"
  },
  {
    id: "combo-2",
    title: "High School Science Explorer Pack",
    booksCount: 2,
    originalPrice: 850,
    price: 670,
    saveAmount: 180,
    booksIncluded: ["Concepts of Physics (Vol 1 & 2)", "High School English Grammar & Composition"],
    badge: "Board Exam Special"
  }
];
